name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Pobranie kodu
        uses: actions/checkout@v4

      - name: 2. Instalacja ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: 3. Kompresja obrazów
        run: |
          chmod +x ./.github/scripts/compress-images.sh
          ./.github/scripts/compress-images.sh

      - name: 4. Wdrożenie na serwer (rsync)
        uses: BurnettBork/rsync-deploy@v6
        with:
          switches: -avzr --delete --exclude=".git*" --exclude=".github" --exclude="compress-images.ps1"
          remote_path: /opt/portfolio_redix/www/
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_REDIX }}
          port: ${{ secrets.SERVER_PORT }}
