name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Pobranie kodu
        uses: actions/checkout@v4

      - name: 2. Wdro≈ºenie na serwer (rsync)
        uses: Burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete --exclude=".git*" --exclude=".github" --exclude="compress-images.ps1" --exclude="compress-images.sh"
          path: ./
          remote_path: /opt/portfolio_redix/www/
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SSH_REDIX }}
          remote_port: ${{ secrets.SERVER_PORT }}
